export const individualdata = [
  { uid: 1, tid: 1, name: "Krishna", ipoints: 100 },
  { uid: 2, tid: 1, name: "Riya", ipoints: 89 },
  { uid: 3, tid: 1, name: "Yuvan", ipoints: 73 },
  { uid: 4, tid: 2, name: "Vivaan", ipoints: 88 },
  { uid: 5, tid: 2, name: "Arjun", ipoints: 83 },
  { uid: 6, tid: 2, name: "Veer", ipoints: 83 },
  { uid: 7, tid: 3, name: "Ishaan", ipoints: 74 },
  { uid: 8, tid: 3, name: "Vihaan", ipoints: 76 },
  { uid: 9, tid: 3, name: "Sara", ipoints: 52 },
  { uid: 10, tid: 4, name: "Manas", ipoints: 87 },
  { uid: 11, tid: 4, name: "Prisha", ipoints: 63 },
  { uid: 12, tid: 4, name: "Nitin", ipoints: 65 },
  { uid: 13, tid: 5, name: "Uday", ipoints: 65 },
  { uid: 14, tid: 5, name: "Krishna", ipoints: 97 },
  { uid: 15, tid: 5, name: "Arjun", ipoints: 83 },
  { uid: 16, tid: 6, name: "Riya", ipoints: 79 },
  { uid: 17, tid: 6, name: "Veer", ipoints: 67 },
  { uid: 18, tid: 6, name: "Shanaya", ipoints: 88 },
  { uid: 19, tid: 6, name: "Pooja", ipoints: 86 },
];
